"""Initial migration

Revision ID: 0f2f727f0150
Revises: 
Create Date: 2026-03-03 09:04:24.714867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f2f727f0150'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kra_pin', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_kra_pin'), 'businesses', ['kra_pin'], unique=True)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'sales', 'accountant', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('branches',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('store_number', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_branch_name'), 'branches', ['branch_name'], unique=False)
    op.create_index(op.f('ix_branches_business_id'), 'branches', ['business_id'], unique=False)
    op.create_table('grns',
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'extracted', 'pending_confirmation', 'confirmed', 'invoiced', 'rejected', name='grnstatus'), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('etims_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('etims_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grns_status'), 'grns', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('lpo_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_email', sa.String(length=255), nullable=True),
    sa.Column('supplier_phone', sa.String(length=50), nullable=True),
    sa.Column('vendor_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'partially_received', 'fully_received', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('store_number', sa.String(length=50), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('order_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('order_date', sa.String(length=50), nullable=True),
    sa.Column('expected_date', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_lpo_number'), 'orders', ['lpo_number'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('etims_invoices',
    sa.Column('grn_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'approved', 'rejected', name='etimsstatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kra_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kra_invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etims_invoices_grn_id'), 'etims_invoices', ['grn_id'], unique=False)
    op.create_index(op.f('ix_etims_invoices_status'), 'etims_invoices', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('etims_invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'mpesa', 'cheque', 'credit', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'reconciled', 'voided', name='paymentstatus'), nullable=False),
    sa.Column('payment_date', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etims_invoice_id'], ['etims_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_etims_invoice_id'), 'payments', ['etims_invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_etims_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_etims_invoices_status'), table_name='etims_invoices')
    op.drop_index(op.f('ix_etims_invoices_grn_id'), table_name='etims_invoices')
    op.drop_table('etims_invoices')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_lpo_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_grns_status'), table_name='grns')
    op.drop_table('grns')
    op.drop_index(op.f('ix_branches_business_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_branch_name'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_kra_pin'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
