"""etims_invoice_business_payment

Revision ID: 5f20419ea0cd
Revises: 0f2f727f0150
Create Date: 2026-03-06 07:16:57.743595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f20419ea0cd'
down_revision: Union[str, None] = '0f2f727f0150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('etims_invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(50), nullable=False),
    sa.Column('payment_date', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['etims_invoice_id'], ['etims_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_etims_invoice_id'), 'payments', ['etims_invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.add_column('branches', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('total_invoiced', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False))
    op.add_column('branches', sa.Column('total_paid', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False))
    op.add_column('businesses', sa.Column('total_invoiced', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False))
    op.add_column('businesses', sa.Column('total_paid', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False))
    op.add_column('etims_invoices', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('etims_invoices', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.add_column('etims_invoices', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('etims_invoices', sa.Column('branch_name', sa.String(length=255), nullable=True))
    op.add_column('etims_invoices', sa.Column('invoice_amount', sa.Float(), nullable=True, comment='Snapshot of confirmed GRN order_total at time of invoice creation'))
    op.add_column('etims_invoices', sa.Column('amount_paid', sa.Float(), server_default='0', nullable=False, comment='Running total of payments received against this invoice'))
    op.create_index(op.f('ix_etims_invoices_branch_id'), 'etims_invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_etims_invoices_business_id'), 'etims_invoices', ['business_id'], unique=False)
    op.create_foreign_key(None, 'etims_invoices', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'etims_invoices', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.add_column('grns', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('grns', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_grns_branch_id'), 'grns', ['branch_id'], unique=False)
    op.create_index(op.f('ix_grns_business_id'), 'grns', ['business_id'], unique=False)
    op.create_foreign_key(None, 'grns', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'grns', 'businesses', ['business_id'], ['id'], ondelete='SET NULL')
    op.execute("""
        ALTER TABLE payments
            ALTER COLUMN payment_method TYPE paymentmethod USING payment_method::paymentmethod,
            ALTER COLUMN status TYPE paymentstatus USING status::paymentstatus
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grns', type_='foreignkey')
    op.drop_constraint(None, 'grns', type_='foreignkey')
    op.drop_index(op.f('ix_grns_business_id'), table_name='grns')
    op.drop_index(op.f('ix_grns_branch_id'), table_name='grns')
    op.drop_column('grns', 'branch_id')
    op.drop_column('grns', 'business_id')
    op.drop_constraint(None, 'etims_invoices', type_='foreignkey')
    op.drop_constraint(None, 'etims_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_etims_invoices_business_id'), table_name='etims_invoices')
    op.drop_index(op.f('ix_etims_invoices_branch_id'), table_name='etims_invoices')
    op.drop_column('etims_invoices', 'amount_paid')
    op.drop_column('etims_invoices', 'invoice_amount')
    op.drop_column('etims_invoices', 'branch_name')
    op.drop_column('etims_invoices', 'business_name')
    op.drop_column('etims_invoices', 'branch_id')
    op.drop_column('etims_invoices', 'business_id')
    op.drop_column('businesses', 'total_paid')
    op.drop_column('businesses', 'total_invoiced')
    op.drop_column('branches', 'total_paid')
    op.drop_column('branches', 'total_invoiced')
    op.drop_column('branches', 'location')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_etims_invoice_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
